CREATE TABLE schueler (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(250) NOT NULL UNIQUE,
    username VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE lehrer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(250) NOT NULL UNIQUE,
    vorname VARCHAR(250) NOT NULL,
    name VARCHAR(250) NOT NULL,
    fach VARCHAR(250) NOT NULL
);

CREATE TABLE bewertung (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sterne INT NOT NULL CHECK (sterne BETWEEN 1 AND 5),
    kommentar TEXT,
    datum DATETIME DEFAULT CURRENT_TIMESTAMP,
    schueler_id INT NOT NULL,
    lehrer_id INT NOT NULL,
    FOREIGN KEY (schueler_id) REFERENCES schueler(id) ON DELETE CASCADE,
    FOREIGN KEY (lehrer_id) REFERENCES lehrer(id) ON DELETE CASCADE
);
